name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Changer selon votre branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build # ou npm run dev, selon comment vous générez votre site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Le répertoire où se trouve votre site généré
